/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author jesus
 */
public class MDI_Food extends javax.swing.JFrame {

    /**
     * Creates new form MDI_Food
     */
    public MDI_Food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        sub_mnu_Sucursal = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sub_mnu_Categoria = new javax.swing.JMenuItem();
        sub_mnu_Platillo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        sub_mnu_Proveedor = new javax.swing.JMenuItem();
        sub_mnu_Prove_Productos = new javax.swing.JMenuItem();
        sub_mnu_Marca = new javax.swing.JMenuItem();
        sub_mnu_Linea = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        sub_mnu_Area = new javax.swing.JMenuItem();
        sub_mnu_Puestos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        sub_mnu_Persona = new javax.swing.JMenuItem();
        sub_mnu_Empleado = new javax.swing.JMenuItem();
        sub_mnu_Cliente = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        sub_mnu_Ventas = new javax.swing.JMenuItem();
        sub_mnu_Detalle_Ventas = new javax.swing.JMenuItem();
        sub_mnu_Corte_Caja = new javax.swing.JMenuItem();
        Mnu_Mis_Datos = new javax.swing.JMenu();
        Sub_mnu_Ver = new javax.swing.JMenuItem();
        Mnu_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/las-compras-en-linea.png"))); // NOI18N
        jMenu2.setText("Sucursal");
        jMenu2.setMargin(new java.awt.Insets(0, 5, 0, 5));

        sub_mnu_Sucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sub_mnu_Sucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/las-compras-en-linea.png"))); // NOI18N
        sub_mnu_Sucursal.setText("Sucursales");
        jMenu2.add(sub_mnu_Sucursal);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/platillo.png"))); // NOI18N
        jMenu1.setText("Platillo");
        jMenu1.setMargin(new java.awt.Insets(0, 10, 0, 10));
        jMenu1.add(jSeparator3);

        sub_mnu_Categoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sub_mnu_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/categoria.png"))); // NOI18N
        sub_mnu_Categoria.setText("Categoria");
        jMenu1.add(sub_mnu_Categoria);

        sub_mnu_Platillo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sub_mnu_Platillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/comida-sana.png"))); // NOI18N
        sub_mnu_Platillo.setText("Platillo");
        jMenu1.add(sub_mnu_Platillo);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/vegetal.png"))); // NOI18N
        jMenu3.setText("Productos");
        jMenu3.setMargin(new java.awt.Insets(0, 10, 0, 10));

        sub_mnu_Proveedor.setText("Proveedor");
        jMenu3.add(sub_mnu_Proveedor);

        sub_mnu_Prove_Productos.setText("Productos");
        jMenu3.add(sub_mnu_Prove_Productos);

        sub_mnu_Marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/marca.png"))); // NOI18N
        sub_mnu_Marca.setText("Marca");
        jMenu3.add(sub_mnu_Marca);

        sub_mnu_Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/linea.png"))); // NOI18N
        sub_mnu_Linea.setText("Linea");
        jMenu3.add(sub_mnu_Linea);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/Cargos.png"))); // NOI18N
        jMenu5.setText("Cargos");
        jMenu5.setMargin(new java.awt.Insets(0, 10, 0, 10));

        sub_mnu_Area.setText("Area");
        jMenu5.add(sub_mnu_Area);

        sub_mnu_Puestos.setText("Puestos");
        jMenu5.add(sub_mnu_Puestos);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/Personal.png"))); // NOI18N
        jMenu4.setText("Personal");
        jMenu4.setMargin(new java.awt.Insets(0, 10, 0, 10));

        sub_mnu_Persona.setText("Persona");
        jMenu4.add(sub_mnu_Persona);

        sub_mnu_Empleado.setText("Empleado");
        jMenu4.add(sub_mnu_Empleado);

        sub_mnu_Cliente.setText("Cliente");
        jMenu4.add(sub_mnu_Cliente);

        jMenuBar1.add(jMenu4);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/Ventas.png"))); // NOI18N
        jMenu7.setText("Ventas");
        jMenu7.setMargin(new java.awt.Insets(0, 10, 0, 10));

        sub_mnu_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/Ventas.png"))); // NOI18N
        sub_mnu_Ventas.setText("Venta");
        jMenu7.add(sub_mnu_Ventas);

        sub_mnu_Detalle_Ventas.setText("Detalles");
        jMenu7.add(sub_mnu_Detalle_Ventas);

        sub_mnu_Corte_Caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/Corte de caja.png"))); // NOI18N
        sub_mnu_Corte_Caja.setText("Corte de Caja");
        jMenu7.add(sub_mnu_Corte_Caja);

        jMenuBar1.add(jMenu7);

        Mnu_Mis_Datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/informacion-personal.png"))); // NOI18N
        Mnu_Mis_Datos.setText("Mis Datos");
        Mnu_Mis_Datos.setMargin(new java.awt.Insets(0, 10, 0, 10));

        Sub_mnu_Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/informacion-personal.png"))); // NOI18N
        Sub_mnu_Ver.setText("Ver");
        Mnu_Mis_Datos.add(Sub_mnu_Ver);

        jMenuBar1.add(Mnu_Mis_Datos);

        Mnu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Botones/salida.png"))); // NOI18N
        Mnu_Salir.setText("Salir");
        Mnu_Salir.setMargin(new java.awt.Insets(0, 200, 0, 10));
        jMenuBar1.add(Mnu_Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Mnu_Mis_Datos;
    public javax.swing.JMenu Mnu_Salir;
    public javax.swing.JMenuItem Sub_mnu_Ver;
    public static final javax.swing.JDesktopPane jDesktopPane1 = new javax.swing.JDesktopPane();
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JMenuItem sub_mnu_Area;
    public javax.swing.JMenuItem sub_mnu_Categoria;
    public javax.swing.JMenuItem sub_mnu_Cliente;
    public javax.swing.JMenuItem sub_mnu_Corte_Caja;
    public javax.swing.JMenuItem sub_mnu_Detalle_Ventas;
    public javax.swing.JMenuItem sub_mnu_Empleado;
    public javax.swing.JMenuItem sub_mnu_Linea;
    public javax.swing.JMenuItem sub_mnu_Marca;
    public javax.swing.JMenuItem sub_mnu_Persona;
    public javax.swing.JMenuItem sub_mnu_Platillo;
    public javax.swing.JMenuItem sub_mnu_Prove_Productos;
    public javax.swing.JMenuItem sub_mnu_Proveedor;
    public javax.swing.JMenuItem sub_mnu_Puestos;
    public javax.swing.JMenuItem sub_mnu_Sucursal;
    public javax.swing.JMenuItem sub_mnu_Ventas;
    // End of variables declaration//GEN-END:variables
}
